version: '3.8'

services:
  # mongodb
  mongo-database:
    image: bitnami/mongodb:6.0-debian-11
    hostname: mongo-database
    container_name: oop-mongo-database
    networks:
      - oop-infra
    volumes:
      - mongo-data:/bitnami/mongodb
    ports:
      - 27018:27017
    environment:
      - ALLOW_EMPTY_PASSWORD=yes

networks:
  oop-infra:
  oop-app:


volumes:
  mongo-data:
