version: '3.8'

services:
  # mysql
  mysql-db:
    image: mysql:debian
    hostname: mysql-db
    networks:
      - oop-infra
    volumes:
      - app-data:/var/lib/mysql
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=mysql@123

  mail-server-smtp:
    image: marcopas/docker-mailslurper
    hostname: mail-server-smtp
    networks:
      - oop-infra
    ports:
      - "2500:2500"
      - "8080:8080"
      - "8085:8085"


networks:
  oop-infra:
  oop-app:


volumes:
  app-data:
