version: '3.8'

services:
  # mongodb
  mongo-database:
    image: bitnami/mongodb:6.0-debian-11
    hostname: mongo-database
    container_name: oop-mongo-database
    networks:
      - oop-infra
    volumes:
      - mongo-data:/bitnami/mongodb
    ports:
      - 27018:27017
    environment:
      - ALLOW_EMPTY_PASSWORD=yes

  mail-server-smtp:
    image: jijiechen/papercut
    hostname: mail-server-smtp
    container_name: oop-mail-server
    networks:
      - oop-infra
    ports:
      - 25:25
      - 37408:37408

networks:
  oop-infra:
  oop-app:


volumes:
  mongo-data:
