name: CI/CD

on:
  push:
    branches: ["main", "master", "develop", "action-workflow"]
  pull_request:
    branches: ["main", "master", "develop"]

jobs:
  build-and-test:
    name: Build and test
    runs-on: ubuntu-20.04

    steps:
      - name: Setup checkout@v3
        uses: actions/checkout@v3

      - name: Setup .NET 6
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: 6.0.x

      - name: Restore dependencies
        working-directory: ${{ secrets.WORKING_DIR }} # working_dir should be folder contain solution file (./service/src)
        run: dotnet restore src.sln

      - name: Build
        working-directory: ${{ secrets.WORKING_DIR }}
        run: dotnet build --no-restore src.sln

      - name: Test
        working-directory: ${{ secrets.WORKING_DIR }}
        run: dotnet test --no-build --verbosity normal src.sln

  docker-build:
    name: Docker build dev
    runs-on: ubuntu-20.04
    needs: [build-and-test]

    steps:
      - name: Setup checkout@v3
        uses: actions/checkout@v3

      - name: Build infra services
        working-directory: ${{ secrets.WORKING_DIR }}
        run: |
          chmod +x ./scripts/github-action/start-compose.sh
          ./scripts/github-action/start-compose.sh
        shell: bash

      - name: Setup cache@v3.0.8
        uses: actions/cache@v3.0.8
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-build-
